# Generated by Django 4.0.4 on 2022-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_bio_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hovercolor',
            field=models.TextField(default='#228B22'),
            preserve_default=False,
        ),
    ]
