# Generated by Django 4.0.4 on 2022-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='weekcolor',
            field=models.JSONField(verbose_name={'Friday': '', 'Monday': '', 'Saturday': '', 'Sunday': '', 'Thursday': '', 'Tuesday': '', 'Wednesday': ''}),
        ),
    ]
