# Generated by Django 4.0.4 on 2022-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile_week_alter_record_weekcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='weekcolor',
            field=models.JSONField(null=True, verbose_name={'Friday': '#808080', 'Monday': '#808080', 'Saturday': '#808080', 'Sunday': '#808080', 'Thursday': '#808080', 'Tuesday': '#808080', 'Wednesday': '#808080'}),
        ),
    ]
