# Generated by Django 4.0.4 on 2022-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dayyear',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
