# Generated by Django 4.0.4 on 2022-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile_dayyear_profile_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(null=True),
        ),
    ]
