# Generated by Django 4.0.4 on 2022-06-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_profile_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(),
        ),
    ]
