# Generated by Django 4.0.4 on 2022-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_profile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='habit',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
